// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bopzezdmtxkejwaxmqtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvcHplemRtdHhrZWp3YXhtcXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTMwODcsImV4cCI6MjA2NTQ4OTA4N30.yqQG-N_J0G_MhDvoFPD2ggPQl0y3xSfUjKLzG0dtI9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);